name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and Deploy to Cloud Run
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16 # Adjust the version as needed

      # Step 3: Install dependencies and build React app
      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      # Step 4: Authenticate with Google Cloud
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCLOUD_AUTH }}

      # Step 5: Set up Google Cloud CLI
      - name: Set up Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCLOUD_PROJECT }}

      # Step 6: Build and push Docker image
      - name: Build and Push Docker Image
        run: |
          gcloud builds submit \
            --tag gcr.io/${{ secrets.GCLOUD_PROJECT }}/${{ secrets.SERVICE_NAME }}

      # Step 7: Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ secrets.SERVICE_NAME }} \
            --image gcr.io/${{ secrets.GCLOUD_PROJECT }}/${{ secrets.SERVICE_NAME }} \
            --region ${{ secrets.GCLOUD_REGION }} \
            --platform managed \
            --allow-unauthenticated
